### ISSUE TITLE
Gravity Form Styles

### ISSUE THREAD

**Issue by mwtsn** [kapow-wp/kapow-theme#33]
@davetgreen suggest we add to the theme a function to disable Gravity Form theme CSS by default and replace it with something that works.

**Comment by mkjonesuk** [comment]
Like this idea @mwtsn - a while ago on a Bootstrap build I used something similar to this:

https://github.com/abrudtkuhl/WordPress-Bootstrap-Gravity-Forms

It basically adds all of the correct form classes to Gravity text boxes, selects, dropdowns, radio buttons etc like `.form-control` 

If we can mimic this with a set of very basic out-of-the box Kapow! form classes that'd be a nice starter pack.
